sudo: required
services:
  - docker

before_install:
  - docker build -t react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true react-docker npm run test

deploy:
  provider: azure_web_apps
  on:
    branch: master